import "./globals.css";
import type { Metadata } from "next";
import { Inter, Rubik } from "next/font/google";


// Components
import { Navbar } from "./components/";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "First Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
