import "./globals.css";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";

// Components

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "First Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        {/* We have this one before but it is now nested in the dashboard and auth*/}
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
